#!/usr/bin/env bash
set -e

cd "$(dirname "$0")"

echo "Création d'une sauvegarde..."
BACKUP="/tmp/yns-demandes-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP"

cp -r src "$BACKUP/"
cp pom.xml "$BACKUP/"

PACKAGE="src/main/java/com/example/catalogue"
TEMPLATES="src/main/resources/templates"
ADMIN_TEMPLATES="$TEMPLATES/admin"
CSS="src/main/resources/static/css/style.css"
PROPERTIES="src/main/resources/application.properties"
SCHEMA="src/main/resources/schema.sql"

mkdir -p "$PACKAGE" "$ADMIN_TEMPLATES"

echo "1. Ajout de la dépendance email..."

python3 <<'PYTHON'
from pathlib import Path

pom = Path("pom.xml")
text = pom.read_text(encoding="utf-8")

if "spring-boot-starter-mail" not in text:
    dependency = """
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>
"""
    text = text.replace("</dependencies>", dependency + "\n    </dependencies>")
    pom.write_text(text, encoding="utf-8")
    print("Dépendance email ajoutée.")
else:
    print("Dépendance email déjà présente.")
PYTHON

echo "2. Création de la table des demandes..."

cat >> "$SCHEMA" <<'EOF'

-- YNS : demandes de produits et offres de prix
CREATE TABLE IF NOT EXISTS demandes_client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_demande VARCHAR(30) NOT NULL,
    annonce_id BIGINT,
    annonce_titre VARCHAR(255),
    nom VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telephone VARCHAR(50),
    produit_recherche VARCHAR(255),
    details TEXT,
    budget DECIMAL(12, 2),
    prix_propose DECIMAL(12, 2),
    message TEXT,
    statut VARCHAR(30) NOT NULL DEFAULT 'NOUVELLE',
    date_demande TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
EOF

echo "3. Configuration des emails..."

cat >> "$PROPERTIES" <<'EOF'

# Notifications par email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

app.mail.to=${MAIL_TO:yanisroum01@gmail.com}
EOF

echo "4. Création du stockage des demandes..."

cat > "$PACKAGE/DemandeClientStore.java" <<'EOF'
package com.example.catalogue;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Set;

@Repository
public class DemandeClientStore {

    private static final Set<String> STATUTS_AUTORISES = Set.of(
        "NOUVELLE",
        "CONTACTEE",
        "ACCEPTEE",
        "REFUSEE"
    );

    private final JdbcTemplate jdbcTemplate;

    public DemandeClientStore(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void enregistrerRecherche(
            String nom,
            String email,
            String telephone,
            String produitRecherche,
            String details,
            BigDecimal budget
    ) {
        jdbcTemplate.update("""
            INSERT INTO demandes_client (
                type_demande,
                nom,
                email,
                telephone,
                produit_recherche,
                details,
                budget,
                statut,
                date_demande
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, 'NOUVELLE', ?)
            """,
            "RECHERCHE_PRODUIT",
            nom,
            email,
            nettoyer(telephone),
            produitRecherche,
            nettoyer(details),
            budget,
            Timestamp.valueOf(LocalDateTime.now())
        );
    }

    public void enregistrerOffre(
            Long annonceId,
            String annonceTitre,
            String nom,
            String email,
            String telephone,
            BigDecimal prixPropose,
            String message
    ) {
        jdbcTemplate.update("""
            INSERT INTO demandes_client (
                type_demande,
                annonce_id,
                annonce_titre,
                nom,
                email,
                telephone,
                prix_propose,
                message,
                statut,
                date_demande
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'NOUVELLE', ?)
            """,
            "OFFRE_PRIX",
            annonceId,
            annonceTitre,
            nom,
            email,
            nettoyer(telephone),
            prixPropose,
            nettoyer(message),
            Timestamp.valueOf(LocalDateTime.now())
        );
    }

    public List<Map<String, Object>> findAll() {
        return jdbcTemplate.queryForList("""
            SELECT *
            FROM demandes_client
            ORDER BY date_demande DESC, id DESC
            """);
    }

    public void changerStatut(Long id, String statut) {
        if (statut == null || !STATUTS_AUTORISES.contains(statut)) {
            throw new IllegalArgumentException("Statut non autorisé");
        }

        jdbcTemplate.update("""
            UPDATE demandes_client
            SET statut = ?
            WHERE id = ?
            """, statut, id);
    }

    public void supprimer(Long id) {
        jdbcTemplate.update(
            "DELETE FROM demandes_client WHERE id = ?",
            id
        );
    }

    private String nettoyer(String valeur) {
        if (valeur == null || valeur.isBlank()) {
            return null;
        }
        return valeur.trim();
    }
}
EOF

echo "5. Création du service d'envoi d'email..."

cat > "$PACKAGE/NotificationMailService.java" <<'EOF'
package com.example.catalogue;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.MailException;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

@Service
public class NotificationMailService {

    private final JavaMailSender mailSender;
    private final String expediteur;
    private final String destinataire;

    public NotificationMailService(
            JavaMailSender mailSender,
            @Value("${spring.mail.username:}") String expediteur,
            @Value("${app.mail.to:yanisroum01@gmail.com}") String destinataire
    ) {
        this.mailSender = mailSender;
        this.expediteur = expediteur;
        this.destinataire = destinataire;
    }

    public boolean envoyer(String sujet, String contenu) {
        if (expediteur == null || expediteur.isBlank()) {
            System.out.println(
                "MAIL_USERNAME absent : demande enregistrée sans notification email."
            );
            return false;
        }

        try {
            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom(expediteur);
            message.setTo(destinataire);
            message.setSubject(sujet);
            message.setText(contenu);

            mailSender.send(message);
            return true;
        } catch (MailException exception) {
            System.err.println(
                "Impossible d'envoyer la notification email : "
                + exception.getMessage()
            );
            return false;
        }
    }
}
EOF

echo "6. Création du contrôleur public..."

cat > "$PACKAGE/DemandeController.java" <<'EOF'
package com.example.catalogue;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.math.BigDecimal;

@Controller
public class DemandeController {

    private final AnnonceStore annonceStore;
    private final DemandeClientStore demandeStore;
    private final NotificationMailService mailService;

    public DemandeController(
            AnnonceStore annonceStore,
            DemandeClientStore demandeStore,
            NotificationMailService mailService
    ) {
        this.annonceStore = annonceStore;
        this.demandeStore = demandeStore;
        this.mailService = mailService;
    }

    @GetMapping("/recherche-produit")
    public String formulaireRecherche(Model model) {
        model.addAttribute("nombrePanier", 0);
        return "demande-produit";
    }

    @PostMapping("/recherche-produit")
    public String enregistrerRecherche(
            @RequestParam String nom,
            @RequestParam String email,
            @RequestParam(required = false) String telephone,
            @RequestParam String produitRecherche,
            @RequestParam(required = false) String details,
            @RequestParam(required = false) String budget,
            Model model
    ) {
        model.addAttribute("nombrePanier", 0);

        BigDecimal montantBudget = convertirMontant(budget);

        if (nom.isBlank() || email.isBlank() || produitRecherche.isBlank()) {
            model.addAttribute(
                "erreur",
                "Veuillez compléter les champs obligatoires."
            );
            return "demande-produit";
        }

        demandeStore.enregistrerRecherche(
            nom.trim(),
            email.trim(),
            telephone,
            produitRecherche.trim(),
            details,
            montantBudget
        );

        String contenu = """
            Nouvelle recherche de produit sur YNS Equipements

            Nom : %s
            Email : %s
            Téléphone : %s
            Produit recherché : %s
            Budget souhaité : %s €
            
            Détails :
            %s
            """.formatted(
                nom,
                email,
                valeurOuNonRenseigne(telephone),
                produitRecherche,
                montantBudget == null ? "Non renseigné" : montantBudget,
                valeurOuNonRenseigne(details)
            );

        boolean emailEnvoye = mailService.envoyer(
            "Nouvelle recherche de produit - YNS Equipements",
            contenu
        );

        model.addAttribute(
            "titreConfirmation",
            "Votre demande a bien été envoyée"
        );
        model.addAttribute(
            "messageConfirmation",
            "Nous allons rechercher le produit correspondant à vos besoins et à votre budget."
        );
        model.addAttribute("emailEnvoye", emailEnvoye);

        return "demande-confirmation";
    }

    @GetMapping("/annonce/{id}/offre")
    public String formulaireOffre(
            @PathVariable Long id,
            Model model
    ) {
        Annonce annonce = annonceStore.findById(id)
            .orElseThrow(() ->
                new IllegalArgumentException("Annonce introuvable")
            );

        model.addAttribute("annonce", annonce);
        model.addAttribute("nombrePanier", 0);

        return "offre-prix";
    }

    @PostMapping("/annonce/{id}/offre")
    public String enregistrerOffre(
            @PathVariable Long id,
            @RequestParam String nom,
            @RequestParam String email,
            @RequestParam(required = false) String telephone,
            @RequestParam String prixPropose,
            @RequestParam(required = false) String message,
            Model model
    ) {
        Annonce annonce = annonceStore.findById(id)
            .orElseThrow(() ->
                new IllegalArgumentException("Annonce introuvable")
            );

        model.addAttribute("annonce", annonce);
        model.addAttribute("nombrePanier", 0);

        BigDecimal montant = convertirMontant(prixPropose);

        if (nom.isBlank() || email.isBlank()) {
            model.addAttribute(
                "erreur",
                "Veuillez renseigner votre nom et votre email."
            );
            return "offre-prix";
        }

        if (montant == null || montant.compareTo(BigDecimal.ZERO) <= 0) {
            model.addAttribute(
                "erreur",
                "Veuillez saisir un prix valide."
            );
            return "offre-prix";
        }

        demandeStore.enregistrerOffre(
            annonce.id(),
            annonce.titre(),
            nom.trim(),
            email.trim(),
            telephone,
            montant,
            message
        );

        String contenu = """
            Nouvelle offre de prix sur YNS Equipements

            Annonce : %s
            Identifiant : %s
            Prix affiché : %s €
            Prix proposé : %s €

            Nom : %s
            Email : %s
            Téléphone : %s

            Message :
            %s
            """.formatted(
                annonce.titre(),
                annonce.id(),
                annonce.prix(),
                montant,
                nom,
                email,
                valeurOuNonRenseigne(telephone),
                valeurOuNonRenseigne(message)
            );

        boolean emailEnvoye = mailService.envoyer(
            "Nouvelle offre pour " + annonce.titre(),
            contenu
        );

        model.addAttribute(
            "titreConfirmation",
            "Votre offre a bien été envoyée"
        );
        model.addAttribute(
            "messageConfirmation",
            "Votre proposition sera étudiée. Une réponse vous sera envoyée par email."
        );
        model.addAttribute("emailEnvoye", emailEnvoye);

        return "demande-confirmation";
    }

    private BigDecimal convertirMontant(String valeur) {
        if (valeur == null || valeur.isBlank()) {
            return null;
        }

        try {
            return new BigDecimal(
                valeur.trim()
                    .replace("€", "")
                    .replace(" ", "")
                    .replace(",", ".")
            );
        } catch (NumberFormatException exception) {
            return null;
        }
    }

    private String valeurOuNonRenseigne(String valeur) {
        if (valeur == null || valeur.isBlank()) {
            return "Non renseigné";
        }
        return valeur.trim();
    }
}
EOF

echo "7. Création du contrôleur d'administration..."

cat > "$PACKAGE/AdminDemandesController.java" <<'EOF'
package com.example.catalogue;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

@Controller
@RequestMapping("/admin/demandes")
public class AdminDemandesController {

    private final DemandeClientStore demandeStore;

    public AdminDemandesController(DemandeClientStore demandeStore) {
        this.demandeStore = demandeStore;
    }

    @GetMapping
    public String demandes(Model model) {
        model.addAttribute("demandes", demandeStore.findAll());
        return "admin/demandes";
    }

    @PostMapping("/{id}/statut")
    public String changerStatut(
            @PathVariable Long id,
            @RequestParam String statut,
            RedirectAttributes redirectAttributes
    ) {
        demandeStore.changerStatut(id, statut);
        redirectAttributes.addFlashAttribute(
            "succes",
            "Le statut de la demande a été modifié."
        );
        return "redirect:/admin/demandes";
    }

    @PostMapping("/{id}/supprimer")
    public String supprimer(
            @PathVariable Long id,
            RedirectAttributes redirectAttributes
    ) {
        demandeStore.supprimer(id);
        redirectAttributes.addFlashAttribute(
            "succes",
            "La demande a été supprimée."
        );
        return "redirect:/admin/demandes";
    }
}
EOF

echo "8. Création du formulaire de recherche..."

cat > "$TEMPLATES/demande-produit.html" <<'EOF'
<!DOCTYPE html>
<html lang="fr" xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Recherche de produit - YNS Equipements</title>
    <link rel="icon" th:href="@{/favicon.png}">
    <link rel="stylesheet" th:href="@{/css/style.css}">
</head>
<body>

<header th:replace="~{fragments :: header}"></header>

<main class="yns-request-page">
    <section class="yns-request-card">
        <span class="yns-request-kicker">Service personnalisé</span>
        <h1>Vous recherchez un produit précis ?</h1>

        <p class="yns-request-intro">
            Décrivez le matériel que vous recherchez, son utilisation
            et votre budget. YNS Equipements étudiera votre demande
            et vous contactera lorsqu'une solution adaptée sera disponible.
        </p>

        <div class="yns-form-error"
             th:if="${erreur}"
             th:text="${erreur}">
        </div>

        <form th:action="@{/recherche-produit}"
              method="post"
              class="yns-request-form">

            <div class="yns-form-grid">
                <label>
                    Nom et prénom *
                    <input type="text"
                           name="nom"
                           required
                           maxlength="150"
                           autocomplete="name">
                </label>

                <label>
                    Adresse email *
                    <input type="email"
                           name="email"
                           required
                           maxlength="255"
                           autocomplete="email">
                </label>

                <label>
                    Téléphone
                    <input type="tel"
                           name="telephone"
                           maxlength="50"
                           autocomplete="tel">
                </label>

                <label>
                    Budget souhaité
                    <div class="yns-price-input">
                        <input type="number"
                               name="budget"
                               min="0"
                               step="0.01"
                               placeholder="Exemple : 150">
                        <span>€</span>
                    </div>
                </label>
            </div>

            <label>
                Produit recherché *
                <input type="text"
                       name="produitRecherche"
                       required
                       maxlength="255"
                       placeholder="Exemple : caméra, carte graphique, dérailleur...">
            </label>

            <label>
                Description de votre besoin
                <textarea name="details"
                          rows="7"
                          maxlength="3000"
                          placeholder="Marque, modèle, état souhaité, caractéristiques, utilisation prévue..."></textarea>
            </label>

            <p class="yns-form-note">
                Aucun paiement n'est demandé pour envoyer cette recherche.
            </p>

            <button type="submit" class="yns-primary-button">
                Envoyer ma recherche
            </button>
        </form>
    </section>
</main>

<footer th:replace="~{fragments :: footer}"></footer>

</body>
</html>
EOF

echo "9. Création du formulaire d'offre..."

cat > "$TEMPLATES/offre-prix.html" <<'EOF'
<!DOCTYPE html>
<html lang="fr" xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Faire une offre - YNS Equipements</title>
    <link rel="icon" th:href="@{/favicon.png}">
    <link rel="stylesheet" th:href="@{/css/style.css}">
</head>
<body>

<header th:replace="~{fragments :: header}"></header>

<main class="yns-request-page">
    <section class="yns-request-card">
        <span class="yns-request-kicker">Proposition de prix</span>
        <h1>Faire une offre</h1>

        <div class="yns-offer-product">
            <img th:src="${annonce.photoPrincipale()}"
                 th:alt="${annonce.titre}">

            <div>
                <span th:text="${annonce.categorie}"></span>
                <h2 th:text="${annonce.titre}"></h2>
                <strong th:text="${annonce.prix + ' €'}"></strong>
            </div>
        </div>

        <p class="yns-request-intro">
            Proposez un prix raisonnable. Votre offre sera étudiée,
            mais son acceptation n'est pas automatique.
        </p>

        <div class="yns-form-error"
             th:if="${erreur}"
             th:text="${erreur}">
        </div>

        <form th:action="@{/annonce/{id}/offre(id=${annonce.id})}"
              method="post"
              class="yns-request-form">

            <div class="yns-form-grid">
                <label>
                    Nom et prénom *
                    <input type="text"
                           name="nom"
                           required
                           maxlength="150">
                </label>

                <label>
                    Adresse email *
                    <input type="email"
                           name="email"
                           required
                           maxlength="255">
                </label>

                <label>
                    Téléphone
                    <input type="tel"
                           name="telephone"
                           maxlength="50">
                </label>

                <label>
                    Votre prix proposé *
                    <div class="yns-price-input">
                        <input type="number"
                               name="prixPropose"
                               min="0.01"
                               step="0.01"
                               required>
                        <span>€</span>
                    </div>
                </label>
            </div>

            <label>
                Message complémentaire
                <textarea name="message"
                          rows="5"
                          maxlength="2000"
                          placeholder="Vous pouvez préciser votre proposition ou poser une question."></textarea>
            </label>

            <p class="yns-form-note">
                Aucun paiement n'est réalisé sur ce site. En cas d'accord,
                la transaction sera finalisée par une plateforme sécurisée
                ou en remise en main propre.
            </p>

            <button type="submit" class="yns-primary-button">
                Envoyer mon offre
            </button>
        </form>
    </section>
</main>

<footer th:replace="~{fragments :: footer}"></footer>

</body>
</html>
EOF

echo "10. Création de la confirmation..."

cat > "$TEMPLATES/demande-confirmation.html" <<'EOF'
<!DOCTYPE html>
<html lang="fr" xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Demande envoyée - YNS Equipements</title>
    <link rel="icon" th:href="@{/favicon.png}">
    <link rel="stylesheet" th:href="@{/css/style.css}">
</head>
<body>

<header th:replace="~{fragments :: header}"></header>

<main class="yns-request-page">
    <section class="yns-confirmation-card">
        <div class="yns-confirmation-icon">✓</div>

        <h1 th:text="${titreConfirmation}">
            Demande envoyée
        </h1>

        <p th:text="${messageConfirmation}">
            Votre demande a bien été enregistrée.
        </p>

        <p class="yns-email-information"
           th:if="${emailEnvoye}">
            Une notification a également été envoyée à YNS Equipements.
        </p>

        <a th:href="@{/}" class="yns-primary-button">
            Retourner à l'accueil
        </a>
    </section>
</main>

<footer th:replace="~{fragments :: footer}"></footer>

</body>
</html>
EOF

echo "11. Création de la page d'administration..."

cat > "$ADMIN_TEMPLATES/demandes.html" <<'EOF'
<!DOCTYPE html>
<html lang="fr" xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Demandes clients - Administration</title>
    <link rel="icon" th:href="@{/favicon.png}">
    <link rel="stylesheet" th:href="@{/css/style.css}">
</head>
<body class="yns-admin-body">

<header class="yns-admin-header">
    <div>
        <strong>YNS Equipements</strong>
        <span>Administration</span>
    </div>

    <nav>
        <a th:href="@{/admin}">Tableau de bord</a>
        <a th:href="@{/admin/annonces}">Annonces</a>
        <a th:href="@{/admin/reservations}">Réservations</a>
        <a th:href="@{/admin/demandes}" class="active">Demandes clients</a>
        <a th:href="@{/}">Voir le site</a>
    </nav>
</header>

<main class="yns-admin-main">
    <div class="yns-admin-title">
        <div>
            <span>Administration</span>
            <h1>Demandes clients et offres</h1>
        </div>
    </div>

    <div class="yns-admin-success"
         th:if="${succes}"
         th:text="${succes}">
    </div>

    <div class="yns-admin-empty" th:if="${#lists.isEmpty(demandes)}">
        Aucune demande client pour le moment.
    </div>

    <div class="yns-demands-grid">
        <article class="yns-demand-card"
                 th:each="demande : ${demandes}">

            <div class="yns-demand-header">
                <span class="yns-demand-type"
                      th:text="${demande['type_demande'] == 'OFFRE_PRIX'
                        ? 'Offre de prix'
                        : 'Recherche de produit'}">
                </span>

                <span class="yns-demand-status"
                      th:text="${demande['statut']}">
                </span>
            </div>

            <h2 th:if="${demande['type_demande'] == 'OFFRE_PRIX'}"
                th:text="${demande['annonce_titre']}">
            </h2>

            <h2 th:if="${demande['type_demande'] == 'RECHERCHE_PRODUIT'}"
                th:text="${demande['produit_recherche']}">
            </h2>

            <div class="yns-demand-information">
                <p>
                    <strong>Client :</strong>
                    <span th:text="${demande['nom']}"></span>
                </p>

                <p>
                    <strong>Email :</strong>
                    <a th:href="${'mailto:' + demande['email']}"
                       th:text="${demande['email']}">
                    </a>
                </p>

                <p th:if="${demande['telephone'] != null}">
                    <strong>Téléphone :</strong>
                    <span th:text="${demande['telephone']}"></span>
                </p>

                <p th:if="${demande['budget'] != null}">
                    <strong>Budget :</strong>
                    <span th:text="${demande['budget'] + ' €'}"></span>
                </p>

                <p th:if="${demande['prix_propose'] != null}">
                    <strong>Prix proposé :</strong>
                    <span th:text="${demande['prix_propose'] + ' €'}"></span>
                </p>

                <p>
                    <strong>Date :</strong>
                    <span th:text="${demande['date_demande']}"></span>
                </p>
            </div>

            <div class="yns-demand-message"
                 th:if="${demande['details'] != null}">
                <strong>Détails de la recherche</strong>
                <p th:text="${demande['details']}"></p>
            </div>

            <div class="yns-demand-message"
                 th:if="${demande['message'] != null}">
                <strong>Message</strong>
                <p th:text="${demande['message']}"></p>
            </div>

            <div class="yns-demand-actions">
                <a class="yns-admin-email-button"
                   th:href="${'mailto:' + demande['email']
                       + '?subject=Votre demande - YNS Equipements'}">
                    Répondre par email
                </a>

                <form th:action="@{/admin/demandes/{id}/statut(id=${demande['id']})}"
                      method="post">
                    <select name="statut">
                        <option value="NOUVELLE"
                                th:selected="${demande['statut'] == 'NOUVELLE'}">
                            Nouvelle
                        </option>
                        <option value="CONTACTEE"
                                th:selected="${demande['statut'] == 'CONTACTEE'}">
                            Contactée
                        </option>
                        <option value="ACCEPTEE"
                                th:selected="${demande['statut'] == 'ACCEPTEE'}">
                            Acceptée
                        </option>
                        <option value="REFUSEE"
                                th:selected="${demande['statut'] == 'REFUSEE'}">
                            Refusée
                        </option>
                    </select>

                    <button type="submit">Modifier</button>
                </form>

                <form th:action="@{/admin/demandes/{id}/supprimer(id=${demande['id']})}"
                      method="post"
                      onsubmit="return confirm('Supprimer définitivement cette demande ?')">
                    <button type="submit" class="yns-delete-button">
                        Supprimer
                    </button>
                </form>
            </div>
        </article>
    </div>
</main>

</body>
</html>
EOF

echo "12. Ajout des boutons sur le site..."

python3 <<'PYTHON'
from pathlib import Path
import re

fragments = Path("src/main/resources/templates/fragments.html")

if fragments.exists():
    text = fragments.read_text(encoding="utf-8")

    if "/recherche-produit" not in text:
        catalogue_link = re.search(
            r'<a[^>]+th:href="@\{/catalogue\}"[^>]*>.*?</a>',
            text,
            flags=re.DOTALL
        )

        link = """
            <a th:href="@{/recherche-produit}">
                Je recherche un produit
            </a>
"""

        if catalogue_link:
            position = catalogue_link.end()
            text = text[:position] + "\n" + link + text[position:]
            fragments.write_text(text, encoding="utf-8")
            print("Lien de recherche ajouté à la navigation.")
        else:
            print("Attention : lien Catalogue introuvable dans fragments.html.")
else:
    print("Attention : fragments.html introuvable.")

annonce = Path("src/main/resources/templates/annonce.html")

if annonce.exists():
    text = annonce.read_text(encoding="utf-8")

    if "/offre" not in text:
        button = """
            <a class="yns-offer-button"
               th:if="${annonce.statut == 'DISPONIBLE'}"
               th:href="@{/annonce/{id}/offre(id=${annonce.id})}">
                Faire une offre
            </a>
"""

        markers = [
            '<div class="actions">',
            '<div class="boutons">',
            '<div class="annonce-actions">'
        ]

        inserted = False

        for marker in markers:
            if marker in text:
                text = text.replace(marker, marker + "\n" + button, 1)
                inserted = True
                break

        if not inserted:
            main_close = text.rfind("</main>")
            if main_close != -1:
                text = text[:main_close] + button + "\n" + text[main_close:]
                inserted = True

        if inserted:
            annonce.write_text(text, encoding="utf-8")
            print("Bouton Faire une offre ajouté.")
        else:
            print("Attention : emplacement du bouton offre introuvable.")
else:
    print("Attention : annonce.html introuvable.")
PYTHON

echo "13. Ajout du design..."

cat >> "$CSS" <<'EOF'

/* =========================================================
   RECHERCHE DE PRODUIT ET OFFRES DE PRIX
   ========================================================= */

.yns-request-page {
    min-height: 70vh;
    padding: 64px 20px 90px;
    background:
        radial-gradient(circle at top right, rgba(37, 99, 235, 0.10), transparent 35%),
        linear-gradient(180deg, #f8fafc 0%, #ffffff 100%);
}

.yns-request-card,
.yns-confirmation-card {
    width: min(820px, 100%);
    margin: 0 auto;
    padding: 42px;
    border: 1px solid #e2e8f0;
    border-radius: 24px;
    background: #ffffff;
    box-shadow: 0 24px 60px rgba(15, 23, 42, 0.09);
}

.yns-request-kicker {
    display: inline-block;
    margin-bottom: 10px;
    color: #2563eb;
    font-size: 0.77rem;
    font-weight: 800;
    letter-spacing: 0.14em;
    text-transform: uppercase;
}

.yns-request-card h1,
.yns-confirmation-card h1 {
    margin: 0 0 16px;
    color: #0f172a;
    font-size: clamp(1.8rem, 4vw, 2.7rem);
    line-height: 1.15;
}

.yns-request-intro {
    margin: 0 0 30px;
    color: #64748b;
    line-height: 1.75;
}

.yns-request-form {
    display: flex;
    flex-direction: column;
    gap: 21px;
}

.yns-form-grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 20px;
}

.yns-request-form label {
    display: flex;
    flex-direction: column;
    gap: 8px;
    color: #0f172a;
    font-size: 0.92rem;
    font-weight: 750;
}

.yns-request-form input,
.yns-request-form textarea,
.yns-demand-actions select {
    width: 100%;
    border: 1px solid #cbd5e1;
    border-radius: 12px;
    color: #0f172a;
    background: #ffffff;
    font: inherit;
    outline: none;
    transition: border-color 160ms ease, box-shadow 160ms ease;
}

.yns-request-form input {
    min-height: 50px;
    padding: 11px 14px;
}

.yns-request-form textarea {
    min-height: 130px;
    padding: 14px;
    resize: vertical;
}

.yns-request-form input:focus,
.yns-request-form textarea:focus,
.yns-demand-actions select:focus {
    border-color: #2563eb;
    box-shadow: 0 0 0 4px rgba(37, 99, 235, 0.11);
}

.yns-price-input {
    display: flex;
    align-items: center;
    overflow: hidden;
    border: 1px solid #cbd5e1;
    border-radius: 12px;
}

.yns-price-input input {
    border: 0;
    border-radius: 0;
    box-shadow: none !important;
}

.yns-price-input span {
    padding: 0 16px;
    color: #475569;
    font-weight: 800;
}

.yns-form-note {
    margin: 0;
    padding: 14px 16px;
    border-radius: 12px;
    color: #475569;
    background: #f1f5f9;
    font-size: 0.88rem;
    line-height: 1.55;
}

.yns-form-error {
    margin-bottom: 22px;
    padding: 14px 16px;
    border: 1px solid #fecaca;
    border-radius: 12px;
    color: #991b1b;
    background: #fef2f2;
    font-weight: 700;
}

.yns-primary-button,
.yns-offer-button {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-height: 50px;
    padding: 12px 22px;
    border: 0;
    border-radius: 13px;
    color: #ffffff;
    background: linear-gradient(135deg, #2563eb, #1e3a8a);
    box-shadow: 0 12px 28px rgba(37, 99, 235, 0.24);
    cursor: pointer;
    font: inherit;
    font-weight: 800;
    text-decoration: none;
    transition: transform 160ms ease, box-shadow 160ms ease;
}

.yns-primary-button:hover,
.yns-offer-button:hover {
    transform: translateY(-2px);
    box-shadow: 0 16px 34px rgba(37, 99, 235, 0.30);
}

.yns-offer-button {
    width: 100%;
    margin: 8px 0;
}

.yns-offer-product {
    display: grid;
    grid-template-columns: 150px 1fr;
    gap: 22px;
    align-items: center;
    margin: 24px 0;
    padding: 18px;
    border: 1px solid #e2e8f0;
    border-radius: 18px;
    background: #f8fafc;
}

.yns-offer-product img {
    width: 150px;
    height: 120px;
    object-fit: contain;
    border-radius: 13px;
    background: #ffffff;
}

.yns-offer-product h2 {
    margin: 7px 0;
    color: #0f172a;
    font-size: 1.3rem;
}

.yns-offer-product span {
    color: #64748b;
    font-size: 0.84rem;
    font-weight: 700;
}

.yns-offer-product strong {
    color: #2563eb;
    font-size: 1.3rem;
}

.yns-confirmation-card {
    text-align: center;
}

.yns-confirmation-card p {
    color: #64748b;
    line-height: 1.7;
}

.yns-confirmation-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 70px;
    height: 70px;
    margin: 0 auto 24px;
    border-radius: 50%;
    color: #ffffff;
    background: #16a34a;
    font-size: 2rem;
    font-weight: 900;
}

.yns-email-information {
    margin-bottom: 28px;
}

/* Administration des demandes */

.yns-admin-body {
    margin: 0;
    color: #0f172a;
    background: #f1f5f9;
}

.yns-admin-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 25px;
    padding: 18px 5%;
    color: #ffffff;
    background: #081a33;
}

.yns-admin-header div {
    display: flex;
    flex-direction: column;
}

.yns-admin-header span {
    color: #93c5fd;
    font-size: 0.78rem;
}

.yns-admin-header nav {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
}

.yns-admin-header nav a {
    padding: 9px 12px;
    border-radius: 9px;
    color: #dbeafe;
    text-decoration: none;
    font-size: 0.88rem;
    font-weight: 700;
}

.yns-admin-header nav a:hover,
.yns-admin-header nav a.active {
    color: #ffffff;
    background: rgba(255, 255, 255, 0.12);
}

.yns-admin-main {
    width: min(1180px, calc(100% - 32px));
    margin: 0 auto;
    padding: 48px 0 80px;
}

.yns-admin-title span {
    color: #2563eb;
    font-size: 0.78rem;
    font-weight: 800;
    letter-spacing: 0.12em;
    text-transform: uppercase;
}

.yns-admin-title h1 {
    margin: 7px 0 30px;
}

.yns-admin-success {
    margin-bottom: 24px;
    padding: 14px 18px;
    border: 1px solid #86efac;
    border-radius: 12px;
    color: #166534;
    background: #f0fdf4;
}

.yns-admin-empty {
    padding: 40px;
    border-radius: 18px;
    text-align: center;
    color: #64748b;
    background: #ffffff;
}

.yns-demands-grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 22px;
}

.yns-demand-card {
    padding: 26px;
    border: 1px solid #e2e8f0;
    border-radius: 20px;
    background: #ffffff;
    box-shadow: 0 14px 35px rgba(15, 23, 42, 0.06);
}

.yns-demand-header {
    display: flex;
    justify-content: space-between;
    gap: 12px;
    margin-bottom: 18px;
}

.yns-demand-type,
.yns-demand-status {
    padding: 7px 10px;
    border-radius: 999px;
    font-size: 0.72rem;
    font-weight: 850;
    text-transform: uppercase;
}

.yns-demand-type {
    color: #1d4ed8;
    background: #dbeafe;
}

.yns-demand-status {
    color: #166534;
    background: #dcfce7;
}

.yns-demand-card h2 {
    margin: 0 0 20px;
    font-size: 1.25rem;
}

.yns-demand-information p {
    margin: 8px 0;
    color: #475569;
}

.yns-demand-information a {
    color: #2563eb;
}

.yns-demand-message {
    margin-top: 18px;
    padding: 15px;
    border-radius: 12px;
    background: #f8fafc;
}

.yns-demand-message p {
    margin: 8px 0 0;
    white-space: pre-line;
    color: #475569;
    line-height: 1.55;
}

.yns-demand-actions {
    display: flex;
    flex-direction: column;
    gap: 10px;
    margin-top: 22px;
}

.yns-demand-actions form {
    display: flex;
    gap: 8px;
}

.yns-demand-actions select {
    min-height: 42px;
    padding: 8px 10px;
}

.yns-demand-actions button,
.yns-admin-email-button {
    min-height: 42px;
    padding: 9px 14px;
    border: 0;
    border-radius: 10px;
    color: #ffffff;
    background: #2563eb;
    cursor: pointer;
    font: inherit;
    font-size: 0.84rem;
    font-weight: 750;
    text-align: center;
    text-decoration: none;
}

.yns-demand-actions form select {
    flex: 1;
}

.yns-delete-button {
    width: 100%;
    background: #dc2626 !important;
}

@media (max-width: 800px) {
    .yns-form-grid,
    .yns-demands-grid {
        grid-template-columns: 1fr;
    }

    .yns-admin-header {
        align-items: flex-start;
        flex-direction: column;
    }
}

@media (max-width: 560px) {
    .yns-request-page {
        padding: 32px 13px 70px;
    }

    .yns-request-card,
    .yns-confirmation-card {
        padding: 26px 18px;
        border-radius: 19px;
    }

    .yns-offer-product {
        grid-template-columns: 95px 1fr;
        gap: 14px;
        padding: 13px;
    }

    .yns-offer-product img {
        width: 95px;
        height: 90px;
    }

    .yns-admin-main {
        width: min(100% - 20px, 1180px);
        padding-top: 28px;
    }

    .yns-demand-card {
        padding: 19px;
    }
}
EOF

echo "14. Vérification de la compilation..."

mvn clean package -DskipTests

echo
echo "======================================================"
echo "MODIFICATION TERMINÉE AVEC SUCCÈS"
echo "======================================================"
echo
echo "Sauvegarde disponible dans : $BACKUP"
echo
echo "Pour tester localement :"
echo
echo "  ADMIN_USERNAME=admin ADMIN_PASSWORD='TonMotDePasse' \\"
echo "  SPRING_PROFILES_ACTIVE=local mvn spring-boot:run"
echo
echo "Pages disponibles :"
echo "  http://localhost:8080/recherche-produit"
echo "  http://localhost:8080/admin/demandes"
echo
