#!/usr/bin/env bash

set -e

cd "$HOME/catalogue-materiel"

echo "Sauvegarde des fichiers actuels..."

BACKUP_DIR="backup-avant-persistance-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"

cp pom.xml "$BACKUP_DIR/"
cp src/main/resources/application.properties "$BACKUP_DIR/"
cp src/main/resources/schema.sql "$BACKUP_DIR/"
cp src/main/java/com/example/catalogue/AdminController.java "$BACKUP_DIR/"

echo "Sauvegarde créée dans : $BACKUP_DIR"

# ============================================================
# Ajouter PostgreSQL et Cloudinary dans pom.xml
# ============================================================

echo "Ajout des dépendances PostgreSQL et Cloudinary..."

python3 <<'PY'
from pathlib import Path

pom = Path("pom.xml")
contenu = pom.read_text(encoding="utf-8")

postgresql = """
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
"""

cloudinary = """
        <dependency>
            <groupId>com.cloudinary</groupId>
            <artifactId>cloudinary-http44</artifactId>
            <version>1.39.0</version>
        </dependency>
"""

dependances = ""

if "<artifactId>postgresql</artifactId>" not in contenu:
    dependances += postgresql

if "<artifactId>cloudinary-http44</artifactId>" not in contenu:
    dependances += cloudinary

if dependances:
    contenu = contenu.replace(
        "    </dependencies>",
        dependances + "\n    </dependencies>",
        1
    )

pom.write_text(contenu, encoding="utf-8")
print("pom.xml mis à jour.")
PY

# ============================================================
# Configuration H2 local / PostgreSQL Render
# ============================================================

echo "Configuration de la base de données..."

cat > src/main/resources/application.properties <<'EOF'
spring.application.name=catalogue-materiel

# En local, l'application utilise H2.
# Sur Render, DB_URL, DB_USERNAME et DB_PASSWORD
# permettront d'utiliser PostgreSQL.
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/catalogue}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

spring.thymeleaf.cache=false

site.admin.username=${ADMIN_USERNAME}
site.admin.password=${ADMIN_PASSWORD}

server.error.include-message=always
EOF

# ============================================================
# Schéma compatible H2 et PostgreSQL
# ============================================================

echo "Création du schéma compatible PostgreSQL..."

cat > src/main/resources/schema.sql <<'EOF'
CREATE TABLE IF NOT EXISTS annonces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR(255) NOT NULL,
    categorie VARCHAR(100) NOT NULL,
    etat VARCHAR(100) NOT NULL,
    prix DECIMAL(10, 2) NOT NULL,
    description TEXT NOT NULL,
    statut VARCHAR(30) NOT NULL,
    lien_vinted VARCHAR(1000),
    lien_leboncoin VARCHAR(1000),
    photos TEXT
);

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telephone VARCHAR(50),
    message TEXT,
    articles TEXT NOT NULL,
    total_indicatif DECIMAL(10, 2),
    date_demande TIMESTAMP NOT NULL,
    traitee BOOLEAN DEFAULT FALSE
);
EOF

# ============================================================
# Service de stockage des images
# Cloudinary sur Render, fichiers locaux en développement
# ============================================================

echo "Création du service de stockage des images..."

cat > src/main/java/com/example/catalogue/ImageStorageService.java <<'EOF'
package com.example.catalogue;

import com.cloudinary.Cloudinary;
import com.cloudinary.utils.ObjectUtils;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

@Service
public class ImageStorageService {

    private static final long TAILLE_MAXIMALE = 10L * 1024L * 1024L;

    private static final Set<String> TYPES_ACCEPTES = Set.of(
        "image/jpeg",
        "image/png",
        "image/webp",
        "image/gif",
        "image/heic",
        "image/heif"
    );

    private final Cloudinary cloudinary;

    public ImageStorageService() {
        String cloudinaryUrl = System.getenv("CLOUDINARY_URL");

        if (cloudinaryUrl == null || cloudinaryUrl.isBlank()) {
            cloudinary = null;

            System.out.println(
                "CLOUDINARY_URL absente : " +
                "les images seront enregistrées localement."
            );
        } else {
            cloudinary = new Cloudinary(cloudinaryUrl);
            cloudinary.config.secure = true;

            System.out.println(
                "Cloudinary est configuré pour le stockage des images."
            );
        }
    }

    public String enregistrer(MultipartFile image) throws IOException {
        verifierImage(image);

        if (cloudinary != null) {
            return envoyerVersCloudinary(image);
        }

        return enregistrerLocalement(image);
    }

    public boolean utiliseCloudinary() {
        return cloudinary != null;
    }

    private void verifierImage(MultipartFile image) {
        if (image == null || image.isEmpty()) {
            throw new IllegalArgumentException(
                "Le fichier image est vide."
            );
        }

        if (image.getSize() > TAILLE_MAXIMALE) {
            throw new IllegalArgumentException(
                "L'image dépasse la limite de 10 Mo."
            );
        }

        String contentType = image.getContentType();

        if (contentType == null ||
                (!contentType.startsWith("image/") &&
                 !TYPES_ACCEPTES.contains(contentType))) {

            throw new IllegalArgumentException(
                "Le fichier sélectionné n'est pas une image valide."
            );
        }
    }

    private String envoyerVersCloudinary(
            MultipartFile image
    ) throws IOException {

        Map<?, ?> resultat = cloudinary.uploader().upload(
            image.getBytes(),
            ObjectUtils.asMap(
                "folder", "yns-equipements",
                "resource_type", "image",
                "use_filename", true,
                "unique_filename", true
            )
        );

        Object secureUrl = resultat.get("secure_url");

        if (secureUrl == null) {
            throw new IOException(
                "Cloudinary n'a retourné aucune URL d'image."
            );
        }

        return secureUrl.toString();
    }

    private String enregistrerLocalement(
            MultipartFile image
    ) throws IOException {

        Path dossier = Path.of("uploads");
        Files.createDirectories(dossier);

        String extension = trouverExtension(
            image.getOriginalFilename()
        );

        String nomFichier =
            UUID.randomUUID() + extension;

        Files.copy(
            image.getInputStream(),
            dossier.resolve(nomFichier),
            StandardCopyOption.REPLACE_EXISTING
        );

        return "/uploads/" + nomFichier;
    }

    private String trouverExtension(String nomOriginal) {
        if (nomOriginal == null || !nomOriginal.contains(".")) {
            return ".jpg";
        }

        String extension = nomOriginal.substring(
            nomOriginal.lastIndexOf(".")
        ).toLowerCase();

        if (extension.length() > 10) {
            return ".jpg";
        }

        return extension;
    }
}
EOF

# ============================================================
# Remplacer automatiquement AdminController
# ============================================================

echo "Modification du contrôleur administrateur..."

cat > src/main/java/com/example/catalogue/AdminController.java <<'EOF'
package com.example.catalogue;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@Controller
@RequestMapping("/admin")
public class AdminController {

    private final AnnonceStore annonceStore;
    private final ReservationStore reservationStore;
    private final ImageStorageService imageStorageService;

    public AdminController(
            AnnonceStore annonceStore,
            ReservationStore reservationStore,
            ImageStorageService imageStorageService
    ) {
        this.annonceStore = annonceStore;
        this.reservationStore = reservationStore;
        this.imageStorageService = imageStorageService;
    }

    @GetMapping
    public String accueilAdmin() {
        return "redirect:/admin/annonces";
    }

    @GetMapping("/annonces")
    public String annonces(Model model) {
        model.addAttribute(
            "annonces",
            annonceStore.findAll()
        );

        return "admin/annonces";
    }

    @GetMapping("/annonces/nouvelle")
    public String nouvelleAnnonce(Model model) {
        model.addAttribute("annonce", null);
        model.addAttribute(
            "cloudinaryActif",
            imageStorageService.utiliseCloudinary()
        );

        return "admin/annonce-form";
    }

    @GetMapping("/annonces/{id}/modifier")
    public String modifierAnnonce(
            @PathVariable Long id,
            Model model
    ) {
        Annonce annonce = annonceStore.findById(id)
                .orElseThrow(() ->
                    new IllegalArgumentException(
                        "Annonce introuvable."
                    )
                );

        model.addAttribute("annonce", annonce);
        model.addAttribute(
            "cloudinaryActif",
            imageStorageService.utiliseCloudinary()
        );

        return "admin/annonce-form";
    }

    @PostMapping("/annonces/enregistrer")
    public String enregistrerAnnonce(
            @RequestParam(required = false) Long id,
            @RequestParam String titre,
            @RequestParam String categorie,
            @RequestParam String etat,
            @RequestParam BigDecimal prix,
            @RequestParam String description,
            @RequestParam String statut,
            @RequestParam(required = false) String lienVinted,
            @RequestParam(required = false) String lienLeboncoin,
            @RequestParam(required = false) String photosUrls,
            @RequestParam(required = false) String photosActuelles,
            @RequestParam(required = false) MultipartFile[] images,
            Model model
    ) {
        try {
            List<String> photos = new ArrayList<>();

            ajouterUrls(
                photos,
                photosActuelles
            );

            ajouterUrls(
                photos,
                photosUrls
            );

            if (images != null) {
                for (MultipartFile image : images) {
                    if (image == null || image.isEmpty()) {
                        continue;
                    }

                    String imageUrl =
                        imageStorageService.enregistrer(image);

                    photos.add(imageUrl);
                }
            }

            annonceStore.save(
                id,
                titre.trim(),
                categorie,
                etat.trim(),
                prix,
                description.trim(),
                statut,
                valeurOuVide(lienVinted),
                valeurOuVide(lienLeboncoin),
                String.join("\n", photos)
            );

            return "redirect:/admin/annonces";

        } catch (IOException |
                 IllegalArgumentException exception) {

            Annonce annonce = new Annonce(
                id,
                titre,
                categorie,
                etat,
                prix,
                description,
                statut,
                valeurOuVide(lienVinted),
                valeurOuVide(lienLeboncoin),
                valeurOuVide(photosActuelles)
            );

            model.addAttribute("annonce", annonce);
            model.addAttribute(
                "erreur",
                exception.getMessage()
            );
            model.addAttribute(
                "cloudinaryActif",
                imageStorageService.utiliseCloudinary()
            );

            return "admin/annonce-form";
        }
    }

    @PostMapping("/annonces/{id}/supprimer")
    public String supprimerAnnonce(
            @PathVariable Long id
    ) {
        annonceStore.delete(id);
        return "redirect:/admin/annonces";
    }

    @GetMapping("/reservations")
    public String reservations(Model model) {
        model.addAttribute(
            "reservations",
            reservationStore.findAll()
        );

        return "admin/reservations";
    }

    @PostMapping("/reservations/{id}/traiter")
    public String traiterReservation(
            @PathVariable Long id
    ) {
        reservationStore.marquerTraitee(id);
        return "redirect:/admin/reservations";
    }

    @PostMapping("/reservations/{id}/supprimer")
    public String supprimerReservation(
            @PathVariable Long id
    ) {
        reservationStore.delete(id);
        return "redirect:/admin/reservations";
    }

    private void ajouterUrls(
            List<String> photos,
            String texte
    ) {
        if (texte == null || texte.isBlank()) {
            return;
        }

        texte.lines()
            .map(String::trim)
            .filter(url -> !url.isBlank())
            .filter(url ->
                url.startsWith("https://") ||
                url.startsWith("http://") ||
                url.startsWith("/uploads/")
            )
            .forEach(photos::add);
    }

    private String valeurOuVide(String valeur) {
        return valeur == null ? "" : valeur.trim();
    }
}
EOF

# ============================================================
# Afficher les erreurs dans le formulaire d'administration
# ============================================================

echo "Ajout de l'affichage des erreurs dans le formulaire..."

python3 <<'PY'
from pathlib import Path

fichier = Path(
    "src/main/resources/templates/admin/annonce-form.html"
)

contenu = fichier.read_text(encoding="utf-8")

bloc = '''
        <div th:if="${erreur}"
             class="information erreur-formulaire"
             th:text="${erreur}">
            Erreur lors de l'enregistrement.
        </div>
'''

if 'th:if="${erreur}"' not in contenu:
    positions = [
        "<h1 th:text=",
        '<input th:if="${annonce != null}"',
        '<label for="titre">'
    ]

    insertion_effectuee = False

    for position in positions:
        index = contenu.find(position)

        if index != -1:
            contenu = (
                contenu[:index] +
                bloc +
                "\n        " +
                contenu[index:]
            )
            insertion_effectuee = True
            break

    if not insertion_effectuee:
        contenu = contenu.replace(
            '<form th:action="@{/admin/annonces/enregistrer}"',
            '<form th:action="@{/admin/annonces/enregistrer}"',
            1
        )

fichier.write_text(contenu, encoding="utf-8")
print("Formulaire d'administration mis à jour.")
PY

# ============================================================
# Styles du message d'erreur
# ============================================================

if ! grep -q "erreur-formulaire" \
    src/main/resources/static/css/style.css
then
    cat >> src/main/resources/static/css/style.css <<'EOF'

.erreur-formulaire {
    margin: 0 0 20px;
    background: #fef2f2;
    color: #991b1b;
    border-color: #fecaca;
}
EOF
fi

# ============================================================
# Compilation
# ============================================================

echo
echo "Compilation du projet..."
echo

export ADMIN_USERNAME="admin"
export ADMIN_PASSWORD="MotDePasseLocalTemporaire123!"

mvn clean package -DskipTests

echo
echo "============================================================"
echo "MODIFICATIONS TERMINÉES"
echo
echo "Le projet compile correctement."
echo
echo "Sauvegarde : $BACKUP_DIR"
echo
echo "Étape suivante : créer PostgreSQL et Cloudinary sur Render."
echo "============================================================"

