spring.application.name=catalogue-materiel

spring.datasource.url=jdbc:h2:file:./data/catalogue
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

spring.thymeleaf.cache=false

site.admin.username=${ADMIN_USERNAME:admin}
site.admin.password=${ADMIN_PASSWORD:ChangeMoi123!}

server.error.include-message=always
