spring.application.name=catalogue-materiel

# En local, l'application utilise H2.
# Sur Render, DB_URL, DB_USERNAME et DB_PASSWORD
# permettront d'utiliser PostgreSQL.
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/catalogue}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

spring.thymeleaf.cache=false

site.admin.username=${ADMIN_USERNAME}
site.admin.password=${ADMIN_PASSWORD}

server.error.include-message=always
